baseURL = "https://gmcintire.github.io"
languageCode = "en-us"
title = "Graham McIntire's thoughts"
theme = "terminal"
paginate = 5
pygmentsCodeFences = true
pygmentsStyle = "monokai"
enableRobotsTXT = true 
enableEmoji = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

[languages]
  [languages.en]
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
